### ISSUE TITLE
Item Page in Menu Gets Weird

### ISSUE THREAD

**Issue by darkphoenixff4** [nathanblair/OblivionControllerCompatibility#4]
Just figured I'd mention, I'm using DarkUI'd DarN, and once I had enough items that the item list disappears below the bottom of the page, the menu gets... strange when the controller controls are used.  Rather than scrolling the item menu to show the items below the bottom, the cursor seems to continue moving down, over the weight and gold icons, and eventually to the lower HUD.  As soon as I move the mouse, everything returns to normal.

**Comment by nathanblair** [comment]
This is always a result of running an instance of the new inventory menu over the classic inventory config file. It's impossible for me to know who's of who's file is being overwritten but assuredly this isn't the behavior you're desiring. When you installed Dark DarN UI did you elect for the new inventory or classic inventory? My suggestion is to go with the classic (and I really can't emphasize it enough - the new inventory scheme is pointless for controllers anyway). And then when you installed UICO, did you choose the same inventory type you chose during the dark DarN installation?

**Comment by nathanblair** [comment]
I'm closing this issue as I have tested my manual install procedure at least a dozen times now and this only happens when the New Inventory is used. The New Inventory is not supported for this mod because it is not within the scope of what this mod aims to adjust.

**Comment by darkphoenixff4** [comment]
Yeah, it's fine.  I noticed after your first post that I didn't install the mod correctly, so I went back and did so.  Haven't gotten a chance to test it, but that's likely what the problem is.
